# config.yml

# Language Settings
# Puedes cambiarlo a "en" según sea necesario
# You can change it to "en" as needed
locale: es

# Generator Settings
# Change ore generation config.
# Cambia la generacion de los fragmentos.
coord_z:
  min: 0
  max: 100

coord_x:
  min: 0
  max: 100
