name: JTunLiveAndDeath
version: 0.2.1
main: com.juanegameryt.jtunliveanddeath.LiveAndDeath
api-version: 1.16
author: JuanEGamerYT
description: Un plugin de Minecraft para Live and Death con funcionalidades especiales.

commands:
  liveanddeath:
    description: Comandos principales de Live and Death.
    usage: /liveanddeath <subcomando>
    aliases: [ldd]

permissions:
  liveanddeath.admin:
    description: Permite a los administradores usar comandos de Live and Death.
    default: op

placeholders:
  fragmentos_conseguidos:
    description: Muestra la cantidad de fragmentos recolectados por el jugador.
  fragmentos_necesarios:
    description: Muestra la cantidad de fragmentos necesarios para escapar.
  players_desterrados:
    description: Muestra la cantidad de jugadores en el mundo desterrado.
  ultima_mena:
    description: Muestra las coordenadas de la última mena de esmeralda generada.
